### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by tanariho** [tanariho/yoga_zukan#71]
お疲れ様です。卒業試験のPF制作のMVPレビュー依頼をいたします。
ご確認お願いいたします🙇‍♀️

### サービス名: ヨガ図鑑
サービスURL: [yoga-zukan.vercel.app](https://yoga-zukan.vercel.app/)
フロントエンド：[yoga-zukan.vercel.app](https://yoga-zukan.vercel.app/)
バックエンド：https://yoga-zukan.onrender.com

GitHubURL:https://github.com/tanariho/yoga_zukan

## 使用技術

**バックエンド**
- Rails 7.0.8
- ruby 3.2.2

**フロントエンド**
- Next.js 13.5.6
- Typescript

**データベース**
- PostgreSQL 15.5

**開発環境**
- Docker

**ライブラリ**
- NextAuth.js

**CSSフレームワーク,　UIライブラリ**

- Tailwind CSS
- PrimeReact

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] 新規会員登録
- [x] ログイン・ログアウト
- [x] ヨガ検定 検定に合格するとヨガポーズが増える(クイズ形式)
- [x] ヨガタイマー ヨガの時間をカウントすると時間に応じてヨガポーズ図鑑の種類が増える
- [x] ヨガポーズ図鑑
- [x] Xシェア

|機能|イメージ|
|:-:|:-:|
|新規会員登録、ログイン・ログアウト|<video src ="https://github.com/tanariho/yoga_zukan/assets/132878326/c9dc28b5-b34f-49d0-9c83-477f95ec13a9">|
|**ヨガ検定**|[![Image from Gyazo](https://i.gyazo.com/84d98f5f69efbfe3bbab5445e0d9fd2e.png)](https://gyazo.com/84d98f5f69efbfe3bbab5445e0d9fd2e)|
問題|[![Image from Gyazo](https://i.gyazo.com/919971745e4895b40da55423b082bcb5.png)](https://gyazo.com/919971745e4895b40da55423b082bcb5)|
ポーズ付与画面(ヨガ検定)|[![Image from Gyazo](https://i.gyazo.com/c862591be45169f5d9fd6d7b1be5524f.png)](https://gyazo.com/c862591be45169f5d9fd6d7b1be5524f)|
**ヨガタイマー**|[![Image from Gyazo](https://i.gyazo.com/93962d6c062c68e3cc57071dc7a12c31.gif)](https://gyazo.com/93962d6c062c68e3cc57071dc7a12c31)|
00:00になるとポーズが付与される|[![Image from Gyazo](https://i.gyazo.com/21461cf5f8aa9c0ab85f9204c92814c1.gif)](https://gyazo.com/21461cf5f8aa9c0ab85f9204c92814c1)|
**ヨガポーズ図鑑**|[![Image from Gyazo](https://i.gyazo.com/3eb031764986afaf0e11b6a33bd32ca5.png)](https://gyazo.com/3eb031764986afaf0e11b6a33bd32ca5)|
詳細表示|[![Image from Gyazo](https://i.gyazo.com/44ce21554bfe90df5167c184c516d99f.png)](https://gyazo.com/44ce21554bfe90df5167c184c516d99f)|
**Xシェア**|[![Image from Gyazo](https://i.gyazo.com/4bd656fd92e0ab6b2e0c18eb165f14a9.png)](https://gyazo.com/4bd656fd92e0ab6b2e0c18eb165f14a9)|
**トップページ**|[![Image from Gyazo](https://i.gyazo.com/e3a99bdcb1ec71e70ee9bb7430121aa7.gif)](https://gyazo.com/e3a99bdcb1ec71e70ee9bb7430121aa7)|

### 変更点：ヨガタイマー
こちらはREADMEではカウントアップ方式ですが、30分のカウントダウン方式に変更いたしました。

お忙しい中恐縮ですが、レビューよろしくお願いいたします！

**Comment by Tsuchiya2** [comment]
サービスのURLが無いようです。ご確認をお願いいたします。

**Comment by tanariho** [comment]
土屋講師
レビューありがとうございます。大変失礼いたしました。
サービスURLはデプロイしたフロントエンドのURLで大丈夫でしょうか？
下にGitHubの方も記載しておきます🙇‍♀️

サービスURL: [yoga-zukan.vercel.app](https://yoga-zukan.vercel.app/)

フロントエンド：[yoga-zukan.vercel.app](https://yoga-zukan.vercel.app/)
バックエンド：https://yoga-zukan.onrender.com

GitHubURL:https://github.com/tanariho/yoga_zukan

**Comment by kenchasonakai** [comment]
開発モード？とかになっていそうなのでご確認お願いします
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/b079d204d9b4c00d255cd041f2737151.png)](https://startup-technology.gyazo.com/b079d204d9b4c00d255cd041f2737151)

**Comment by tanariho** [comment]
@kenchasonakai 
なかい講師
ご確認ありがとうございます。Google CloudのOauth設定を本番環境に切り替えましたので、お手数ですが再度ご確認よろしくお願いいたします。

**Comment by tanariho** [comment]
@kenchasonakai 
ご確認ありがとうございます😭
これからも頑張ります！！！PFレビュー会もよろしくお願いいたします🙇‍♀️
