### ISSUE TITLE
提出物レビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [tanariho/yoga_zukan#84]
お疲れ様でした。
講師陣でレビューしたところ、
一定水準以上の技術力とWebアプリの完成度があるとの評価になりました。

このまますぐに就活に入っても問題ない&評価を受けやすい状態ですので、就職活動の準備を進めましょう！
引き続き頑張ってください！

**Comment by tanariho** [comment]
@Tsuchiya2 
土屋講師
早速のレビューありがとうございます！
引き続き頑張ります！よろしくお願いいたします！🙇‍♀️
